version: '3.8'

services:
  web:
    build: ./docker/streamlit/
    command: streamlit run app.py
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    networks:
      - digit
    depends_on:
      - db

  db:
    image: ./docker/db/
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - digit

volumes:
  postgres_data:

networks:
  digit:
    external:
      name: digit