version: '3.8'

services:
  web:
    build: ./docker/streamlit/
    command: streamlit run app.py
    volumes:
      - .:/app
    ports:
      - 8501:8501
    env_file:
      - ./.env
    networks:
      - charity
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
        #environment:
        #- POSTGRES_USER=hello_django
        #- POSTGRES_PASSWORD=hello_django
        #- POSTGRES_DB=hello_django_dev
    networks:
      - charity

volumes:
  postgres_data:

networks:
  charity:
    external:
      name: charity
